[build]
  publish = ".next"
  command = "npm run build"
[[edge_functions]]
  function = "bookeo-proxy"
  path = "/bookeo-proxy"
[[edge_functions]]
  function = "waiver-sign"
  path = "/waiver-sign"
[[edge_functions]]
  function = "waiver-submit"
  path = "/waiver-submit"
[[edge_functions]]
  function = "waiver-validate"
  path = "/waiver-validate"
[[edge_functions]]
  function = "redis"
  path = "/redis"
[[edge_functions]]
  path = "/analytics/bookings"
  function = "booking-analytics"