[build]
  publish = ".next"
  command = "npm run build"
[[edge_functions]]
  function = "bookeo-proxy"
  path = "/bookeo-proxy"
[[edge_functions]]
  function = "submit-proxy"
  path = "/submit-proxy"
